Link to Excel file of extracted features: https://drive.google.com/drive/u/1/folders/1ZMbW7HxNkBUAlnT-_lXLD4J_r0A778SJ

In [2]:
# import required packages
import pandas as pd

In [3]:
# open csv with meditative states
ck_med = pd.read_excel('CK_med.xlsx', index_col=None, header=0)
ck_med['label'] = 'ck_med'
ck_med = ck_med.drop(labels = ['Total Power','SDNN'], axis = 1)
ck_med

,Abs LFP,Abs HFP,nLFP,nHFP,LF/HF,RMSSD,label
0,2191.200278,7531.913277,0.213938,0.735378,0.290922,884.187257,ck_med
1,1868.670157,7793.285696,0.184287,0.768567,0.239780,865.110274,ck_med
2,1660.286319,7725.558626,0.167196,0.777988,0.214908,841.936312,ck_med
3,1588.519882,7744.244474,0.160756,0.783707,0.205123,842.584333,ck_med
4,1790.083067,7312.760284,0.185830,0.759145,0.244789,826.156703,ck_med
...,...,...,...,...,...,...,...
139,223.552939,813.610805,0.192702,0.701331,0.274766,735.611693,ck_med
140,275.481168,1015.442748,0.193928,0.714831,0.271292,766.606858,ck_med
141,196.719824,1092.517596,0.141124,0.783755,0.180061,779.975532,ck_med
142,253.493676,906.193736,0.199998,0.714956,0.279735,760.283782,ck_med
143,280.524877,833.522461,0.231084,0.686618,0.336553,769.641956,ck_med

In [4]:
# open csv with non-meditative states
ck_pre = pd.read_excel('CK_pre.xlsx', index_col=None, header=0)
ck_pre['label'] = 'ck_pre'
ck_pre = ck_pre.drop(labels = ['Total Power','SDNN'], axis = 1)
ck_pre

,Abs LFP,Abs HFP,nLFP,nHFP,LF/HF,RMSSD,label
0,3249.551607,8043.922163,0.271662,0.672470,0.403976,932.714731,ck_pre
1,2022.717898,6829.397915,0.219590,0.741411,0.296178,803.437128,ck_pre
2,2378.753676,6678.590063,0.256223,0.719372,0.356176,793.228617,ck_pre
3,2431.402950,7008.622545,0.243283,0.701272,0.346916,865.589904,ck_pre
4,1897.800009,7150.309660,0.197731,0.744987,0.265415,852.451001,ck_pre
...,...,...,...,...,...,...,...
139,662.027791,1154.416138,0.332828,0.580371,0.573474,1460.906582,ck_pre
140,702.767596,1205.732791,0.330470,0.566985,0.582855,1470.412199,ck_pre
141,567.190494,1057.476732,0.301442,0.562012,0.536362,1417.982428,ck_pre
142,275.600103,1092.574487,0.190182,0.753946,0.252248,1210.602823,ck_pre
143,357.754224,1044.882642,0.238099,0.695408,0.342387,1433.815043,ck_pre

In [5]:
df = pd.concat([ck_pre,ck_med])
df

,Abs LFP,Abs HFP,nLFP,nHFP,LF/HF,RMSSD,label
0,3249.551607,8043.922163,0.271662,0.672470,0.403976,932.714731,ck_pre
1,2022.717898,6829.397915,0.219590,0.741411,0.296178,803.437128,ck_pre
2,2378.753676,6678.590063,0.256223,0.719372,0.356176,793.228617,ck_pre
3,2431.402950,7008.622545,0.243283,0.701272,0.346916,865.589904,ck_pre
4,1897.800009,7150.309660,0.197731,0.744987,0.265415,852.451001,ck_pre
...,...,...,...,...,...,...,...
139,223.552939,813.610805,0.192702,0.701331,0.274766,735.611693,ck_med
140,275.481168,1015.442748,0.193928,0.714831,0.271292,766.606858,ck_med
141,196.719824,1092.517596,0.141124,0.783755,0.180061,779.975532,ck_med
142,253.493676,906.193736,0.199998,0.714956,0.279735,760.283782,ck_med
143,280.524877,833.522461,0.231084,0.686618,0.336553,769.641956,ck_med

In [6]:
# save df into a csv file
df.to_csv('v2_ck_features.csv',index=False)